### ISSUE TITLE
to-do list

### ISSUE THREAD

**Issue by msricher** [theochem/matrix-permanent#7]
I pushed some changes to the [`michelle`](https://github.com/theochem/matrix-permanent/tree/michelle) branch. It broke the Ryser algorithm, but that's fixable...

Here's what's left to do:

## Tuning the function to choose the best algorithm

* See [`run_tuning.c`](https://github.com/theochem/matrix-permanent/blob/michelle/permanent/run_tuning.c) which determines the parameters for the code to choose the best algorithm, and writes them to a header file when `run_tuning` is executed. We need to work out how we want to determine the best algorithm, and then write the code to determine the appropriate parameters. You can also output some benchmarks into that file, as C comments, which would be useful.

* See [`permanent.c`](https://github.com/theochem/matrix-permanent/blob/michelle/permanent/permanent.c#L8) which includes this header if `TUNING_FILE` is defined. If it's not defined, the parameters are given some default values. When we compile the final C and Python libraries, we define `TUNING_FILE` using a C compiler flag, e.g. `gcc -DTUNING_FILE=1 ...`. We need to write better default parameters, as well as write proper code in the function `opt` to choose the best algorithm using the tuning parameters (my code for this is just nonsense).

* See also the [`Makefile`](https://github.com/theochem/matrix-permanent/blob/michelle/Makefile) to understand how the entire compilation is done.

## Support complex type

* Use macros to support `complex double` type. I'll do this if Paul wants.

## Cleaning up the code

* Can we split up the square and rectangular parts of the Glynn and Ryser algorithms into two shorter functions in `permanent.c`?

* Let's try to make things a bit faster. In C, sizes of things are unsigned (I'm sure you got the `size_t` lecture for example) so let's do that where possible. And you can use `int` in most places since the matrices won't have M or N greater than 64.

* Clean up the code and comments.

* Do something with the stuff in `old_tools/`.

## Writing documentation

* Adapt the documentation in `old_docs` to the Python Sphinx-Doc format in `docs`.

* Make sure version/author/website/etc. fields in `setup.py`, `Makefile`, etc. are up to date.

**Comment by PaulWAyers** [comment]
Minor comments:
1. I **do** like to have `complex double`. Yes please.
2. I imagine that M=N=64 is the max, but I can imagine being interested in M=10 (~20 electrons) with N=100 (100 basis functions). If it isn't a huge problem, I'd probably prefer a slightly bigger integer then. But I'm a bit confused, because it seems to me that an unsigned `short int` should go from 0 to 2^16-1 (16 bits), which is a gracious plenty. I didn't see a 1-byte int type, but I may be missing something.

**Comment by cassmasschelein** [comment]
I have fixed the broken Ryser algorithm, split the square and rectangular ryser and glynn algorithms and added a conditional inside py_permanent.c for the shape

**Comment by cassmasschelein** [comment]
What do we think about running a multiclass support vector machine on the output for the fastest algorithm to get the decision boundary and use those parameters for the optimization?
